server:
  port: 4000
spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mybatis/sql/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml