server:
  port: 9047
spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demo
    username: root
    password: root

mybatis:
  mapper-locations: classpath:sqlmap/**/*.xml
  config-location: classpath:mybatis-config.xml